[package]
name = "advent-of-code-2024-day-01"
version = "1.0.0"
edition = "2021"

[profile.dev]
opt-level = 3
incremental = true

[profile.release]
opt-level = 3

[dependencies]
clap={ version = "3.2.23", features = ["derive"] }
